import { Service, Team, Testimonial, BlogPost, PricingTier } from '@/types';

export const SERVICES: Service[] = [
  {
    id: '1',
    name: 'Hair Cut & Style',
    slug: 'hair-cut-style',
    description: 'Professional haircut with personalized styling',
    longDescription: 'Experience our signature haircut service with expert stylists who understand your unique hair type and personal style. We use premium products and techniques to ensure your cut lasts longer and looks impeccable.',
    price: 85,
    duration: '45-60 min',
    image: '/images/service-hair-cut.jpg',
    category: 'hair',
    benefits: ['Expert consultation', 'Premium products', 'Personalized style', 'Long-lasting results'],
  },
  {
    id: '2',
    name: 'Color Treatment',
    slug: 'color-treatment',
    description: 'Vibrant, long-lasting color with premium dyes',
    longDescription: 'Our color specialists use only the finest Italian and French color brands to achieve stunning, natural-looking results. Whether you want subtle highlights or a complete transformation, we deliver excellence.',
    price: 150,
    duration: '90-120 min',
    image: '/images/service-color.jpg',
    category: 'hair',
    benefits: ['Consultation included', 'Premium color brands', 'Root touch-up options', 'Color care products'],
  },
  {
    id: '3',
    name: 'Bridal Makeup',
    slug: 'bridal-makeup',
    description: 'Radiant, wedding-day perfect makeup',
    longDescription: 'Our makeup artists specialize in creating the perfect bridal look that photographs beautifully and lasts all day. We offer trials, touch-ups, and complete customization to match your vision.',
    price: 200,
    duration: '60 min',
    image: '/images/service-bridal.jpg',
    category: 'makeup',
    benefits: ['Trial session', 'Long-lasting formula', 'Touch-up kit', 'Professional photography'],
  },
  {
    id: '4',
    name: 'Manicure & Pedicure',
    slug: 'manicure-pedicure',
    description: 'Complete nail care with gel or polish options',
    longDescription: 'Indulge in our luxurious nail services featuring premium brands like OPI and Sally Hansen. Choose from our extensive color collection or bring your own design.',
    price: 65,
    duration: '60 min',
    image: '/images/service-nails.jpg',
    category: 'nails',
    benefits: ['Premium brands', 'Gel or polish options', 'Design customization', 'Relaxation experience'],
  },
  {
    id: '5',
    name: 'Facial Treatment',
    slug: 'facial-treatment',
    description: 'Revitalizing facial with customized skincare',
    longDescription: 'Our facials use premium skincare products tailored to your skin type. Experience deep cleansing, exfoliation, and hydration for glowing, healthy skin.',
    price: 120,
    duration: '50 min',
    image: '/images/service-facial.jpg',
    category: 'wellness',
    benefits: ['Skin analysis', 'Premium products', 'Customized treatment', 'Skincare consultation'],
  },
  {
    id: '6',
    name: 'Massage Therapy',
    slug: 'massage-therapy',
    description: 'Therapeutic massage to relieve tension',
    longDescription: 'Our licensed massage therapists provide Swedish, deep tissue, and hot stone massages. Perfect for relaxation, stress relief, and muscle recovery.',
    price: 110,
    duration: '60 min',
    image: '/images/service-massage.jpg',
    category: 'wellness',
    benefits: ['Licensed therapists', 'Multiple techniques', 'Aromatherapy options', 'Wellness consultation'],
  },
];

export const TEAM: Team[] = [
  {
    id: '1',
    name: 'Sofia Rossi',
    role: 'Creative Director & Lead Stylist',
    bio: 'With over 15 years of experience in luxury salons across Europe and New York, Sofia brings an artistic vision to every client interaction.',
    image: '/images/team-sofia.jpg',
    specialties: ['Hair Color', 'Styling', 'Texture Treatments'],
    experience: 15,
    social: { instagram: '#', linkedin: '#' },
  },
  {
    id: '2',
    name: 'Marcus Thompson',
    role: 'Senior Hair Stylist',
    bio: 'Specializing in precision cuts and transformative styling, Marcus is known for his meticulous attention to detail and creative flair.',
    image: '/images/team-marcus.jpg',
    specialties: ['Men\'s Cuts', 'Precision Cutting', 'Styling'],
    experience: 12,
    social: { instagram: '#', linkedin: '#' },
  },
  {
    id: '3',
    name: 'Elena Martinez',
    role: 'Master Makeup Artist',
    bio: 'Elena has trained internationally and works with high-profile clients for special events and photoshoots. Her signature look combines elegance with modern trends.',
    image: '/images/team-elena.jpg',
    specialties: ['Bridal Makeup', 'Event Makeup', 'Special FX'],
    experience: 10,
    social: { instagram: '#', linkedin: '#' },
  },
  {
    id: '4',
    name: 'Aisha Patel',
    role: 'Lead Esthetician',
    bio: 'Certified in advanced skincare treatments and wellness practices, Aisha creates personalized skincare journeys for each client.',
    image: '/images/team-aisha.jpg',
    specialties: ['Facials', 'Skincare', 'Wellness'],
    experience: 9,
    social: { instagram: '#', linkedin: '#' },
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Jessica Chen',
    role: 'Business Executive',
    content: 'The team transformed my hair and I felt like a new person walking out of there. Sofia truly understood my vision and delivered beyond expectations.',
    rating: 5,
    image: '/images/testimonial-1.jpg',
    service: 'Hair Color & Style',
  },
  {
    id: '2',
    name: 'Amanda Brooks',
    role: 'Bride',
    content: 'My wedding makeup was absolutely perfect. Elena made me feel beautiful and confident on the most important day of my life. Highly recommended!',
    rating: 5,
    image: '/images/testimonial-2.jpg',
    service: 'Bridal Makeup',
  },
  {
    id: '3',
    name: 'Sarah Johnson',
    role: 'Marketing Director',
    content: 'I\'ve been coming here for two years and the consistency in quality is unmatched. The team treats you like family and takes time to understand your needs.',
    rating: 5,
    image: '/images/testimonial-3.jpg',
    service: 'Regular Client',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Summer Hair Care Guide: Protecting Your Locks from Sun Damage',
    slug: 'summer-hair-care-guide',
    excerpt: 'Learn how to protect your hair from UV damage and chlorine this summer season.',
    content: 'Summer sun can be harsh on your hair. Here are the best practices to keep your locks looking healthy and vibrant throughout the season.',
    author: 'Sofia Rossi',
    date: '2024-06-15',
    category: 'Hair Care',
    image: '/images/blog-1.jpg',
    readTime: 5,
  },
  {
    id: '2',
    title: 'The Art of the Perfect Eyebrow: A Complete Guide',
    slug: 'perfect-eyebrow-guide',
    excerpt: 'Discover the techniques and products that create the perfect eyebrow shape for your face.',
    content: 'Your eyebrows frame your face. Learn how to shape, fill, and maintain them for maximum impact.',
    author: 'Elena Martinez',
    date: '2024-06-10',
    category: 'Makeup',
    image: '/images/blog-2.jpg',
    readTime: 7,
  },
  {
    id: '3',
    title: 'Skincare Routine Essentials: 10-Step Korean Beauty',
    slug: 'korean-skincare-routine',
    excerpt: 'Explore the benefits of the Korean 10-step skincare routine and how to adapt it to your needs.',
    content: 'Korean skincare emphasizes prevention and hydration. Discover the 10 essential steps for glowing skin.',
    author: 'Aisha Patel',
    date: '2024-06-05',
    category: 'Skincare',
    image: '/images/blog-3.jpg',
    readTime: 8,
  },
];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: '1',
    name: 'Monthly Pass',
    description: 'Perfect for regular salon visits',
    price: 199,
    period: 'month',
    features: [
      'One free haircut',
      '15% discount on all services',
      'Priority booking',
      'Exclusive member events',
    ],
  },
  {
    id: '2',
    name: 'Premium Plus',
    description: 'Our most popular plan',
    price: 399,
    period: 'month',
    popular: true,
    features: [
      'Two free haircuts',
      '20% discount on all services',
      'Priority booking + phone line',
      'Complimentary styling products',
      'VIP access to new treatments',
      'Free consultations',
    ],
  },
  {
    id: '3',
    name: 'Elite Concierge',
    description: 'Ultimate luxury experience',
    price: 699,
    period: 'month',
    features: [
      'Unlimited haircuts',
      'Unlimited treatments',
      'Personal stylist assigned',
      'White-glove service',
      'Complimentary luxury products',
      'Priority same-day booking',
      'Home service available',
    ],
  },
];

export const NAVIGATION = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Services', href: '/services' },
  { label: 'Gallery', href: '/gallery' },
  { label: 'Team', href: '/team' },
  { label: 'Testimonials', href: '/testimonials' },
  { label: 'Blog', href: '/blog' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'Contact', href: '/contact' },
];
